# ===============================================================
# BANCO DE DADOS
# ===============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/pdv
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================================================
# FLYWAY
# ===============================================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/


# ===============================================================
# JPA / HIBERNATE
# ===============================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================================================
# DEBUG FLYWAY
# ===============================================================
#logging.level.org.flywaydb=DEBUG
#logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

