# ===============================================================
# CONFIGURAÇÃO DO BANCO DE DADOS (POSTGRESQL)
# ===============================================================
# Altere 'nome_do_seu_banco' para o banco que você criou no Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/pdv
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================================================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# ===============================================================
# Cria/atualiza as tabelas automaticamente de acordo com as classes Java
spring.jpa.hibernate.ddl-auto=update

# Mostra as instruções SQL formatadas no terminal do Neovim
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Otimiza os comandos especificamente para a sintaxe do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

